print ("Faça um programa que leia um numero inteiro, e mostre na tela a sua tabuada")

num = int(input("digite um numero "))
print ("Tabuada: ")
print (f"1x - {num}")
print (f"2x - {num * 2}")
print (f"3x - {num * 3}")
print (f"4x - {num * 4}")
print (f"5x - {num * 5}")
print (f"6x - {num * 6}")
print (f"7x - {num * 7}")
print (f"8x - {num * 8}")
print (f"9x - {num * 9}")
print (f"10x - {num * 10}")
